# Generated by Django 4.2.3 on 2023-07-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='categoy',
            new_name='category',
        ),
    ]
